{% set name = "geotile" %}
{% set version = "1.1.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98d08dbda7011a624fa93ea43e97001c801985dccf04f495b98e1a7c7f144979

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - pip
    - numpy
    - fiona
    - gdal
    - geopandas
    - rasterio

test:
  imports:
    - geotile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iamtekson/geotile
  license: MIT
  license_file: LICENSE
  summary: The package for management of geographic raster tiles.
  description: |
    The geotile package is useful for the manipulation of geospatial raster tiles. 
  dev_url: https://github.com/iamtekson/geotile

extra:
  recipe-maintainers:
    - iamtekson
